ALTER TABLE `payroll_settings`
  ADD COLUMN `late_count_rule` SMALLINT UNSIGNED NULL,
  ADD COLUMN `minimum_salary_allowed` DECIMAL(12, 2) NULL,
  ADD COLUMN `timezone` VARCHAR(100) NULL;

ALTER TABLE `salaries`
  ADD COLUMN `working_days` SMALLINT UNSIGNED NOT NULL DEFAULT 0,
  ADD COLUMN `present_days` SMALLINT UNSIGNED NOT NULL DEFAULT 0,
  ADD COLUMN `leave_days` SMALLINT UNSIGNED NOT NULL DEFAULT 0;
