'use strict';
const { Prisma } = require('@prisma/client'); const { prisma } = require('../../config/database'); const { ApiError } = require('../../utils/ApiError');
const include = { teacher: { select: { id: true, name: true, loginId: true } }, branch: { select: { id: true, name: true, code: true } }, class: { select: { id: true, name: true } } };
const dbDate = value => new Date(`${value}T00:00:00.000Z`); const dateKey = value => value.toISOString().slice(0, 10);
const serializeReport = value => value ? ({ ...value, id: String(value.id), teacherId: String(value.teacherId), branchId: String(value.branchId), classId: String(value.classId), reportDate: dateKey(value.reportDate), periodStart: dateKey(value.periodStart), periodEnd: dateKey(value.periodEnd), teacher: value.teacher ? { ...value.teacher, id: String(value.teacher.id) } : undefined, branch: value.branch ? { ...value.branch, id: String(value.branch.id) } : undefined, class: value.class ? { ...value.class, id: String(value.class.id) } : undefined }) : null;
const validatePeriod = input => { const reportDate = dbDate(input.reportDate); const start = dbDate(input.periodStart); const end = dbDate(input.periodEnd); if ([reportDate,start,end].some(value => Number.isNaN(value.getTime())) || start > end || reportDate < start || reportDate > end) throw new ApiError(422, 'INVALID_REPORT_PERIOD', 'Report period is invalid.'); if (input.reportType === 'DAILY' && (start.getTime() !== reportDate.getTime() || end.getTime() !== reportDate.getTime())) throw new ApiError(422, 'INVALID_REPORT_PERIOD', 'Daily report must cover one day.'); if (input.reportType === 'WEEKLY' && (start.getUTCDay() !== 1 || end.getUTCDay() !== 0 || (end-start)/86400000 !== 6)) throw new ApiError(422, 'INVALID_REPORT_PERIOD', 'Weekly report must cover Monday through Sunday.'); if (input.reportType === 'MONTHLY' && (start.getUTCDate() !== 1 || end.getUTCMonth() !== start.getUTCMonth() || end.getUTCFullYear() !== start.getUTCFullYear() || new Date(Date.UTC(end.getUTCFullYear(), end.getUTCMonth()+1, 0)).getUTCDate() !== end.getUTCDate())) throw new ApiError(422, 'INVALID_REPORT_PERIOD', 'Monthly report must cover a calendar month.'); return { reportDate, periodStart: start, periodEnd: end }; };
const listWhere = (query, teacherId) => ({ ...(teacherId ? { teacherId: BigInt(teacherId) } : {}), ...(query.teacherId ? { teacherId: BigInt(query.teacherId) } : {}), ...(query.branchId ? { branchId: BigInt(query.branchId) } : {}), ...(query.classId ? { classId: BigInt(query.classId) } : {}), ...(query.reportType ? { reportType: query.reportType } : {}), ...((query.dateFrom || query.dateTo) ? { reportDate: { ...(query.dateFrom ? { gte: dbDate(query.dateFrom) } : {}), ...(query.dateTo ? { lte: dbDate(query.dateTo) } : {}) } } : {}) });
const createReportService = (database, options = {}) => { const now = options.now || (() => new Date()); const list = async (query, teacherId) => { const where = listWhere(query, teacherId); const skip = (query.page-1)*query.limit; const [items,total] = await database.$transaction([database.teacherReport.findMany({ where, include, orderBy: { submittedAt: 'desc' }, skip, take: query.limit }), database.teacherReport.count({ where })]); return { items: items.map(serializeReport), pagination: { page: query.page, limit: query.limit, total, totalPages: Math.max(1,Math.ceil(total/query.limit)) } }; }; const find = async (id, teacherId) => { const value = await database.teacherReport.findFirst({ where: { id: BigInt(id), ...(teacherId ? { teacherId: BigInt(teacherId) } : {}) }, include }); if (!value) throw new ApiError(404,'REPORT_NOT_FOUND','Report was not found.'); return value; }; return {
  async create(teacherId,input) { const period=validatePeriod(input); const teacher=await database.user.findFirst({ where:{ id:BigInt(teacherId),role:'TEACHER',status:'ACTIVE' },select:{id:true,branchId:true,classId:true,teacherType:true} }); if(teacher?.teacherType==='SUPERVISOR') throw new ApiError(403,'TEACHER_FORM_ONLY','This form is available only to Teachers.'); if(!teacher||!teacher.branchId||!teacher.classId) throw new ApiError(409,'TEACHER_ASSIGNMENT_INCOMPLETE','Teacher requires a branch and class assignment.'); const submittedAt=now(); try { return serializeReport(await database.teacherReport.create({ data:{teacherId:teacher.id,branchId:teacher.branchId,classId:teacher.classId,reportType:input.reportType,...period,contentJson:input.contentJson,submittedAt,editableUntil:new Date(submittedAt.getTime()+3600000)},include })); } catch(error) { if(error instanceof Prisma.PrismaClientKnownRequestError&&error.code==='P2002') throw new ApiError(409,'REPORT_ALREADY_EXISTS','A report already exists for this period.'); throw error; } },
  mine:(teacherId,query)=>list(query,teacherId), admin:query=>list(query), async detail(id,teacherId){return serializeReport(await find(id,teacherId));}, async update(id,input,actor){const current=await find(id,actor.role==='TEACHER'?actor.userId:null); if(actor.role==='TEACHER'&&now()>=current.editableUntil) throw new ApiError(409,'REPORT_EDIT_EXPIRED','The report edit window has expired.'); return serializeReport(await database.teacherReport.update({where:{id:current.id},data:{contentJson:input.contentJson},include}));}, async export(query){return (await database.teacherReport.findMany({where:listWhere(query),include,orderBy:{submittedAt:'desc'},take:10000})).map(serializeReport);}
}; };
const reportService=createReportService(prisma); module.exports={createReportService,listWhere,reportService,serializeReport,validatePeriod};
