'use strict';
const fs = require('node:fs'); const path = require('node:path');
const { applicationDefault, cert, getApps, initializeApp } = require('firebase-admin/app'); const { getAuth } = require('firebase-admin/auth'); const { getFirestore } = require('firebase-admin/firestore');
const { PrismaClient } = require('@prisma/client'); const { hashPassword } = require('../utils/password');
const { attendanceStatus, createReport, dateKeyInTimezone, normalizeLoginId, normalizeRole, randomUnknownPassword, toDate, validDateKey } = require('./firebaseMigration.utils');
const options = Object.fromEntries(process.argv.slice(2).map(arg => { const [key, ...value] = arg.split('='); return [key, value.join('=') || true]; })); const execute = options['--execute'] === true; if (execute && options['--confirm'] !== 'FIREBASE_TO_MYSQL') throw new Error('Execution requires --confirm=FIREBASE_TO_MYSQL. Omit --execute for dry-run.');
const serviceAccount = options['--service-account'] || process.env.FIREBASE_SERVICE_ACCOUNT_PATH; const mappingFile = options['--mapping'] || path.join(__dirname, 'firebase-mapping.json'); const reportFile = options['--report'] || path.join(process.cwd(), 'migration-reports', `firebase-${new Date().toISOString().replace(/[:.]/g, '-')}.json`); const timezone = options['--timezone'] || process.env.APP_TIMEZONE || 'Asia/Karachi';
const readJson = file => JSON.parse(fs.readFileSync(path.resolve(file), 'utf8')); const mapping = fs.existsSync(mappingFile) ? readJson(mappingFile) : { branches: {}, classes: {}, collections: {} }; const credential = serviceAccount ? cert(readJson(serviceAccount)) : applicationDefault(); const firebaseApp = getApps()[0] || initializeApp({ credential }); const auth = getAuth(firebaseApp); const firestore = getFirestore(firebaseApp); const prisma = new PrismaClient(); const report = createReport();
const userCollection = mapping.collections?.users || 'users'; const attendanceCollection = mapping.collections?.attendance || 'daily_attendance'; const plannedUsers = new Map(); let dryRunId = -1n; const bump = (section, key) => { report[section][key] += 1; }; const value = (object, ...keys) => keys.map(key => object?.[key]).find(item => item !== undefined && item !== null); const mappedId = (type, source) => source == null ? null : mapping[type]?.[String(source)] || null; const text = input => input == null ? null : String(input);
const loadAuthUsers = async () => { const result = new Map(); let token; do { const page = await auth.listUsers(1000, token); page.users.forEach(user => result.set(user.uid, user)); token = page.pageToken; } while (token); return result; };
const loadProfiles = async () => { const snapshot = await firestore.collection(userCollection).get(); return new Map(snapshot.docs.map(doc => [doc.id, { id: doc.id, ...doc.data() }])); };
const migrateUsers = async () => { const [authUsers, profiles] = await Promise.all([loadAuthUsers(), loadProfiles()]); for (const uid of new Set([...authUsers.keys(), ...profiles.keys()])) { bump('users', 'scanned'); try { const authUser = authUsers.get(uid), profile = profiles.get(uid) || {}; const role = normalizeRole(value(profile, 'role', 'user_role')); if (!role) { bump('users', 'skipped'); report.warnings.push({ type: 'USER_UNKNOWN_ROLE', uid, role: profile.role ?? null }); continue; } if (await prisma.user.findUnique({ where: { legacyFirebaseUid: uid } })) { bump('users', 'duplicates'); continue; }
    const email = text(value(profile, 'email') || authUser?.email)?.trim().toLowerCase() || null; const loginId = normalizeLoginId(value(profile, 'loginId', 'login_id') || authUser?.email?.split('@')[0] || uid); const conflict = await prisma.user.findFirst({ where: { OR: [{ loginId }, ...(email ? [{ email }] : [])] }, select: { id: true } }); if (conflict) { bump('users', 'duplicates'); report.warnings.push({ type: 'USER_UNIQUE_CONFLICT', uid, mysqlUserId: String(conflict.id), loginId, email }); continue; }
    const branchId = mappedId('branches', value(profile, 'branchId', 'branch_id')), classId = mappedId('classes', value(profile, 'classId', 'class_id')); const data = { name: text(value(profile, 'name', 'displayName') || authUser?.displayName || authUser?.email || uid), loginId, email, passwordHash: await hashPassword(randomUnknownPassword()), contact: text(value(profile, 'contact', 'phone') || authUser?.phoneNumber), role, branchId: branchId ? BigInt(branchId) : null, classId: classId ? BigInt(classId) : null, timing: text(value(profile, 'timing')), baseSalary: null, status: 'INACTIVE', legacyFirebaseUid: uid };
    if (execute) { const created = await prisma.user.create({ data, select: { id: true } }); plannedUsers.set(uid, { id: created.id, branchId: data.branchId, classId: data.classId }); report.importedUserIds.push(String(created.id)); } else { plannedUsers.set(uid, { id: dryRunId--, branchId: data.branchId, classId: data.classId }); } bump('users', 'imported');
  } catch (error) { bump('users', 'errors'); report.errors.push({ type: 'USER_IMPORT_ERROR', uid, code: error.code || error.name, message: error.message }); } } };
const resolveTeacher = async record => { const uid = value(record, 'teacherId', 'teacher_id', 'employeeId', 'employee_id', 'uid'); if (!uid) return null; return plannedUsers.get(String(uid)) || prisma.user.findUnique({ where: { legacyFirebaseUid: String(uid) }, select: { id: true, branchId: true, classId: true } }); };
const migrateAttendance = async () => { const snapshot = await firestore.collection(attendanceCollection).get(); for (const document of snapshot.docs) { bump('attendance', 'scanned'); try { const record = document.data(), legacyFirebaseId = document.id; if (await prisma.teacherAttendance.findUnique({ where: { legacyFirebaseId } })) { bump('attendance', 'duplicates'); continue; } const teacher = await resolveTeacher(record); if (!teacher) { bump('attendance', 'skipped'); report.warnings.push({ type: 'ATTENDANCE_UNKNOWN_TEACHER', id: document.id }); continue; }
    const checkInAt = toDate(value(record, 'checkInAt', 'check_in_at', 'checkIn', 'check_in')), checkOutAt = toDate(value(record, 'checkOutAt', 'check_out_at', 'checkOut', 'check_out')); const rawDate = value(record, 'attendanceDate', 'attendance_date', 'date'), parsedDate = toDate(rawDate); const key = validDateKey(rawDate) || (parsedDate ? dateKeyInTimezone(parsedDate, timezone) : null) || (checkInAt ? dateKeyInTimezone(checkInAt, timezone) : null); if (!key) throw new Error('Attendance date cannot be resolved.'); const attendanceDate = new Date(`${key}T00:00:00.000Z`); const duplicate = await prisma.teacherAttendance.findUnique({ where: { teacherId_attendanceDate: { teacherId: teacher.id, attendanceDate } }, select: { id: true } }); if (duplicate) { bump('attendance', 'duplicates'); report.warnings.push({ type: 'ATTENDANCE_DATE_CONFLICT', id: document.id, mysqlAttendanceId: String(duplicate.id) }); continue; }
    const branch = mappedId('branches', value(record, 'branchId', 'branch_id')), classItem = mappedId('classes', value(record, 'classId', 'class_id')), late = value(record, 'isLate', 'is_late'); const data = { teacherId: teacher.id, branchId: branch ? BigInt(branch) : teacher.branchId, classId: classItem ? BigInt(classItem) : teacher.classId, legacyFirebaseId, attendanceDate, timingSnapshot: text(value(record, 'timingSnapshot', 'timing')), checkInAt, checkOutAt, isLate: typeof late === 'boolean' ? late : null, status: attendanceStatus(record), leaveRequestId: null };
    if (execute) { const created = await prisma.teacherAttendance.create({ data, select: { id: true } }); report.importedAttendanceIds.push(String(created.id)); } bump('attendance', 'imported');
  } catch (error) { bump('attendance', 'errors'); report.errors.push({ type: 'ATTENDANCE_IMPORT_ERROR', id: document.id, code: error.code || error.name, message: error.message }); } } };
const writeReport = () => { const target = path.resolve(reportFile); fs.mkdirSync(path.dirname(target), { recursive: true }); fs.writeFileSync(target, `${JSON.stringify({ mode: execute ? 'execute' : 'dry-run', timezone, collections: { users: userCollection, attendance: attendanceCollection }, ...report }, null, 2)}\n`, { mode: 0o600 }); return target; };
(async () => { await migrateUsers(); await migrateAttendance(); process.stdout.write(`Firebase migration ${execute ? 'EXECUTE' : 'DRY-RUN'} complete. Report: ${writeReport()}\n`); })().catch(error => { report.errors.push({ type: 'FATAL', code: error.code || error.name, message: error.message }); process.stderr.write(`Migration failed. Report: ${writeReport()}\n`); process.exitCode = 1; }).finally(() => prisma.$disconnect());
